global:
  scrape_interval: 15s  # Adjust scrape interval as needed

scrape_configs:
  - job_name: 'haproxy'
    metrics_path: /metrics
    static_configs:
      - targets: ['172.17.0.2:8404']  # IP Address Or Host of HAProxy Docker containers
